services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mi-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: mi-postgres
    environment:
      POSTGRES_USER: abcd
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: abcd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abcd -d abcd"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafanaaa
    ports:
      - "8080:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

  api:
    build: ./api
    image: imagen-api-iot
    container_name: mi-api-iot
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

  frontend:
    build: ./frontend
    image: imagen-frontend-iot
    container_name: mi-frontend-iot
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api

volumes:
  postgres_data: